# Generated by Django 3.1 on 2020-08-29 11:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(default=0)),
                ('names', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=None), size=None)),
                ('board_size', models.IntegerField(default=24)),
                ('n_characters', models.IntegerField(default=0)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(default=None, upload_to=''), size=None)),
                ('flipped1', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), size=24)),
                ('flipped2', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), size=24)),
                ('turn', models.IntegerField(default=1)),
            ],
        ),
    ]
