# Generated by Django 3.1 on 2020-08-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_ready',
            field=models.IntegerField(default=0),
        ),
    ]
